apiVersion: v1
kind: page
spec:
  id: sHHQB98
  title: Image Demo
  content:
    - component: codeComponent.ImageListComponent
      name: codeComponent_ImageListComponent
      props:
        columns:
          xs: 1
          sm: 4
          md: 4
          lg: 4
          xl: 4
        type: belowtitle
        titlePosition: top
        variant: quilted
        heading: Standard | 4 column | below title
        imageData:
          $$jsExpression: |
            imagelist.data.list1
        subHeading: yurtyrty
        headingVariant: h3
        subHeadingVariant: h5
    - component: codeComponent.ImageListComponent
      name: codeComponent_ImageListComponent1
      props:
        heading: masonry | 3 column | bottom title
        headingVariant: h6
        subHeading: for images that have different sizes
        titlePosition: bottom
        imageData:
          $$jsExpression: |
            imagelist.data.list2
        variant: standard
        columns:
          xs: 1
          sm: 2
          md: 3
          lg: 4
          xl: 4
        subHeadingVariant: body1
    - component: codeComponent.ImageListComponent
      name: codeComponent_ImageListComponent2
      props:
        heading: quilted (row setting per item) | 4 column | top
        titlePosition: top
        variant: quilted
        columns:
          xs: 1
          sm: 3
          md: 3
          lg: 3
          xl: 3
        subHeading: spanning columns and rows per image
        imageData:
          $$jsExpression: |
            imagelist.data.list1
        headingVariant: h6
        subHeadingVariant: body1
    - component: codeComponent.ImageListComponent
      name: codeComponent_ImageListComponent3
      props:
        imageData:
          - img: https://images.unsplash.com/photo-1551963831-b3b1ca40c98e
            title: Breakfast
            author: "@updatedAuthor"
            featured: true
          - img: https://images.unsplash.com/photo-1551782450-a2132b4ba21d
            title: Burger
            author: "@rollelflex_graphy726"
          - img: https://images.unsplash.com/photo-1522770179533-24471fcdba45
            title: Camera
            author: "@helloimnik"
          - img: https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c
            title: Coffee
            author: "@nolanissac"
            cols: 2
          - img: https://images.unsplash.com/photo-1533827432537-70133748f5c8
            title: Hats
            author: "@hjrc33"
            cols: 2
          - img: https://images.unsplash.com/photo-1558642452-9d2a7deb7f62
            title: Honey
            author: "@arwinneil"
            featured: true
          - img: https://images.unsplash.com/photo-1516802273409-68526ee1bdd6
            title: Basketball
            author: "@tjdragotta"
          - img: https://images.unsplash.com/photo-1518756131217-31eb79b20e8f
            title: Fern
            author: "@katie_wasserman"
          - img: https://images.unsplash.com/photo-1597645587822-e99fa5d45d25
            title: Mushrooms
            author: "@silverdalex"
          - img: https://images.unsplash.com/photo-1567306301408-9b74779a11af
            title: Tomato basil
            author: "@shelleypauls"
          - img: https://images.unsplash.com/photo-1471357674240-e1a485acb3e1
            title: Sea star
            author: "@peterlaster"
          - img: https://images.unsplash.com/photo-1589118949245-7d38baf380d6
            title: Bike
            author: "@southside_customs"
  queries:
    - name: imagelist
      query:
        kind: rest
        url: https://api.npoint.io/c59eab6bc0a03aa1e0b7
        searchParams: []
        headers: []
        method: GET
  display: shell
